# Generated by Django 6.0.6 on 2026-06-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Institution Categories',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(help_text='Custom partnership ID e.g. BPS-021, PART002', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_role', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('status', models.CharField(choices=[('STRATEGIC', 'Strategic Partner'), ('EMERGING', 'Emerging Partner'), ('STANDARD', 'Standard Partner')], default='STANDARD', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('has_internship', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('has_joint_research', models.BooleanField(default=False)),
                ('has_staff_exchange', models.BooleanField(default=False)),
                ('has_grant_writing', models.BooleanField(default=False)),
                ('has_lab_training', models.BooleanField(default=False)),
                ('has_curriculum_dev', models.BooleanField(default=False)),
                ('has_funding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='supporting_institutions', to='academics.course')),
                ('departments', models.ManyToManyField(blank=True, related_name='collaborating_institutions', to='academics.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='organizations.institutioncategory')),
            ],
        ),
    ]
