import os
from django.core.management.base import BaseCommand
from modules.organizations.models import InstitutionCategory, Institution, PartnerStatus

class Command(BaseCommand):
    help = "Seeds database with 10 institution categories and popular institutions from spreadsheet"

    def handle(self, *args, **options):
        # 1. Categories
        categories_data = [
            ("Government Agency", "Ministries, departments, and executive government entities collaborating on national scales."),
            ("Research Institution", "Public and private research laboratories, institutes, and organizations focused on scientific advancements."),
            ("Private Industry", "Commercial entities and corporations across agriculture, tech, services, and trade."),
            ("Manufacturing Company", "Industrial manufacturing plants and processing factories."),
            ("Health Institution", "Hospitals, medical centers, and national referral facilities."),
            ("Regulatory Body", "Statutory boards and agencies overseeing compliance, standards, and licensing."),
            ("NGO & Development Partner", "Non-governmental organizations and international development foundations."),
            ("Professional Body", "Societies, colleges, and associations setting professional standards."),
            ("Educational Institution", "Schools, colleges, and training academies."),
            ("International Organization", "Multilateral, globally-coordinated agencies and UN bodies."),
        ]

        categories = {}
        for name, desc in categories_data:
            cat, created = InstitutionCategory.objects.get_or_create(
                name=name,
                defaults={"description": desc}
            )
            categories[name] = cat
            if created:
                self.stdout.write(self.style.SUCCESS(f"Category '{name}' created."))

        # 2. Institutions data
        institutions_data = [
            # Government Agencies
            {
                "custom_id": "GOV001",
                "name": "Kenya Bureau of Standards (KEBS)",
                "category_name": "Government Agency",
                "county": "Nairobi",
                "contact_email": "info@kebs.org",
                "contact_phone": "+254 20 6948000",
                "website": "https://www.kebs.org",
                "description": "National standards body managing quality assurance and standards compliance.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": False,
                "has_funding": False,
            },
            {
                "custom_id": "GOV002",
                "name": "Kenya Plant Health Inspectorate Service (KEPHIS)",
                "category_name": "Government Agency",
                "county": "Nairobi",
                "contact_email": "info@kephis.org",
                "contact_phone": "+254 20 3536171",
                "website": "https://www.kephis.org",
                "description": "Government regulatory agency for plant health, seeds, and agricultural quality control.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            {
                "custom_id": "GOV003",
                "name": "Government Chemist Department",
                "category_name": "Government Agency",
                "county": "Nairobi",
                "contact_email": "info@govchem.go.ke",
                "contact_phone": "+254 20 2725227",
                "website": "https://www.governmentchemist.go.ke",
                "description": "National laboratory providing forensic, toxicology, and chemical analysis services.",
                "status": PartnerStatus.STANDARD,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": False,
                "has_funding": False,
            },
            {
                "custom_id": "GOV004",
                "name": "National Environment Management Authority (NEMA)",
                "category_name": "Government Agency",
                "county": "Nairobi",
                "contact_email": "info@nema.go.ke",
                "contact_phone": "+254 20 2101370",
                "website": "https://www.nema.go.ke",
                "description": "Environmental management agency coordinating national ecological conservation.",
                "status": PartnerStatus.STANDARD,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            {
                "custom_id": "GOV005",
                "name": "Kenya Wildlife Service (KWS)",
                "category_name": "Government Agency",
                "county": "Nairobi",
                "contact_email": "info@kws.go.ke",
                "contact_phone": "+254 20 6000800",
                "website": "https://www.kws.go.ke",
                "description": "Conservation body protecting and managing wildlife populations and national parks.",
                "status": PartnerStatus.EMERGING,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            {
                "custom_id": "GOV006",
                "name": "Kenya Forestry Research Institute (KEFRI)",
                "category_name": "Government Agency",
                "county": "Kiambu",
                "contact_email": "info@kefri.org",
                "contact_phone": "+254 722 157414",
                "website": "https://www.kefri.org",
                "description": "National institute conducting scientific research in forestry and ecological systems.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            # Research Institutions
            {
                "custom_id": "RES001",
                "name": "Kenya Medical Research Institute (KEMRI)",
                "category_name": "Research Institution",
                "county": "Nairobi",
                "contact_email": "info@kemri.go.ke",
                "contact_phone": "+254 20 2722541",
                "website": "https://www.kemri.go.ke",
                "description": "State corporation responsible for conducting research in human health and development.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            {
                "custom_id": "RES002",
                "name": "International Centre of Insect Physiology and Ecology (icipe)",
                "category_name": "Research Institution",
                "county": "Nairobi",
                "contact_email": "icipe@icipe.org",
                "contact_phone": "+254 20 8632000",
                "website": "https://www.icipe.org",
                "description": "International scientific research center specializing in entomology and insect ecology.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            {
                "custom_id": "RES003",
                "name": "Kenya Agricultural and Livestock Research Organization (KALRO)",
                "category_name": "Research Institution",
                "county": "Nairobi",
                "contact_email": "info@kalro.org",
                "contact_phone": "+254 20 4183301",
                "website": "https://www.kalro.org",
                "description": "Leading agricultural and livestock research body in Kenya.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            {
                "custom_id": "RES004",
                "name": "International Livestock Research Institute (ILRI)",
                "category_name": "Research Institution",
                "county": "Nairobi",
                "contact_email": "info@ilri.org",
                "contact_phone": "+254 20 4223000",
                "website": "https://www.ilri.org",
                "description": "Co-hosted global research center focused on livestock health and food security.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            # Private Industries & Manufacturing
            {
                "custom_id": "PRI001",
                "name": "Brookside Dairy Limited",
                "category_name": "Private Industry",
                "county": "Kiambu",
                "contact_email": "info@brookside.co.ke",
                "contact_phone": "+254 67 22000",
                "website": "https://www.brookside.co.ke",
                "description": "Leading milk and dairy processing factory in East Africa.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": False,
                "has_funding": False,
            },
            {
                "custom_id": "PRI002",
                "name": "Del Monte Kenya Limited",
                "category_name": "Private Industry",
                "county": "Murang'a",
                "contact_email": "info@delmonte.co.ke",
                "contact_phone": "+254 67 31251",
                "website": "https://www.delmonte.co.ke",
                "description": "Large agricultural cultivation, fruit juice, and canning processing factory.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            {
                "custom_id": "MAN001",
                "name": "Bamburi Cement PLC",
                "category_name": "Manufacturing Company",
                "county": "Mombasa",
                "contact_email": "info@bamburi.lafarge.com",
                "contact_phone": "+254 20 2893000",
                "website": "https://www.lafarge.co.ke",
                "description": "Primary industrial manufacturing company for building materials and cement.",
                "status": PartnerStatus.STANDARD,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": False,
                "has_funding": False,
            },
            # Health Institutions
            {
                "custom_id": "HEA001",
                "name": "Kenyatta National Hospital (KNH)",
                "category_name": "Health Institution",
                "county": "Nairobi",
                "contact_email": "info@knh.or.ke",
                "contact_phone": "+254 20 2726300",
                "website": "https://knh.or.ke",
                "description": "Largest national referral and medical teaching hospital in Kenya.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            {
                "custom_id": "HEA002",
                "name": "Moi Teaching and Referral Hospital (MTRH)",
                "category_name": "Health Institution",
                "county": "Uasin Gishu",
                "contact_email": "info@mtrh.go.ke",
                "contact_phone": "+254 53 2033471",
                "website": "https://www.mtrh.go.ke",
                "description": "Second largest national referral and medical research facility in Eldoret.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            # Regulatory Bodies
            {
                "custom_id": "REG001",
                "name": "National Commission for Science, Technology and Innovation (NACOSTI)",
                "category_name": "Regulatory Body",
                "county": "Nairobi",
                "contact_email": "info@nacosti.go.ke",
                "contact_phone": "+254 20 4007000",
                "website": "https://www.nacosti.go.ke",
                "description": "Regulatory board coordinating scientific research authorization and licensing in Kenya.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            # NGOs & Development Partners
            {
                "custom_id": "NGO001",
                "name": "AMREF Health Africa",
                "category_name": "NGO & Development Partner",
                "county": "Nairobi",
                "contact_email": "info@amref.org",
                "contact_phone": "+254 20 6993000",
                "website": "https://amref.org",
                "description": "Largest African-based international health development non-governmental organization.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            {
                "custom_id": "NGO002",
                "name": "World Vision Kenya",
                "category_name": "NGO & Development Partner",
                "county": "Nairobi",
                "contact_email": "info@wvi.org",
                "contact_phone": "+254 20 3883652",
                "website": "https://www.wvi.org/kenya",
                "description": "International humanitarian development and child sponsorship NGO.",
                "status": PartnerStatus.STANDARD,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": False,
                "has_funding": True,
            },
            # Professional Bodies
            {
                "custom_id": "PRC001",
                "name": "Kenya Society for Biochemistry and Molecular Biology (KSBMB)",
                "category_name": "Professional Body",
                "county": "Nairobi",
                "contact_email": "info@ksbmb.org",
                "website": "https://www.ksbmb.org",
                "description": "Professional body bringing together bio-scientists, molecular biologists, and chemists.",
                "status": PartnerStatus.STANDARD,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            # Educational Institutions
            {
                "custom_id": "EDU001",
                "name": "Kenya School of Government (KSG)",
                "category_name": "Educational Institution",
                "county": "Nairobi",
                "contact_email": "info@ksg.ac.ke",
                "contact_phone": "+254 20 4015000",
                "website": "https://www.ksg.ac.ke",
                "description": "State corporation offering training, research, and advisory services for public service.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": False,
            },
            # International Organizations
            {
                "custom_id": "INT001",
                "name": "World Health Organization (WHO) Kenya",
                "category_name": "International Organization",
                "county": "Nairobi",
                "contact_email": "afrokenya@who.int",
                "website": "https://www.who.int",
                "description": "Multilateral international specialized agency managing global public health projects.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            },
            {
                "custom_id": "INT002",
                "name": "Food and Agriculture Organization (FAO) Kenya",
                "category_name": "International Organization",
                "county": "Nairobi",
                "contact_email": "fao-ke@fao.org",
                "website": "https://www.fao.org",
                "description": "United Nations specialized agency leading international efforts to defeat hunger and support agriculture.",
                "status": PartnerStatus.STRATEGIC,
                "has_internship": True,
                "has_attachment": True,
                "has_joint_research": True,
                "has_funding": True,
            }
        ]

        for item in institutions_data:
            cat = categories[item["category_name"]]
            inst, created = Institution.objects.get_or_create(
                custom_id=item["custom_id"],
                defaults={
                    "name": item["name"],
                    "category": cat,
                    "county": item["county"],
                    "contact_email": item["contact_email"],
                    "contact_phone": item.get("contact_phone", "Available on website"),
                    "website": item.get("website", ""),
                    "description": item["description"],
                    "status": item["status"],
                    "has_internship": item["has_internship"],
                    "has_attachment": item["has_attachment"],
                    "has_joint_research": item["has_joint_research"],
                    "has_funding": item["has_funding"],
                }
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"Institution '{item['name']}' created successfully."))
            else:
                self.stdout.write(f"Institution '{item['name']}' already exists.")

        self.stdout.write(self.style.SUCCESS("Database seeding completed successfully!"))
