# Generated by Django 6.0.6 on 2026-06-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=15)),
                ('signed_by_university', models.CharField(max_length=150)),
                ('signed_by_institution', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MoU',
                'verbose_name_plural': 'MoUs',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('MOU', 'Memorandum of Understanding (MoU)'), ('REPORT', 'Report'), ('LETTER', 'Attachment/Internship Letter'), ('ANNOUNCEMENT', 'Public Announcement'), ('OTHER', 'Other Document')], default='OTHER', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='organizations.institution')),
            ],
        ),
    ]
