# Generated by Django 6.0.6 on 2026-06-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('ATTACHMENT', 'Student Attachment'), ('RESEARCH', 'Research Collaboration'), ('FUNDING', 'Funding Opportunity')], max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('slots', models.PositiveIntegerField(default=1)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional funding amount (KES or USD)', max_digits=12, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='organizations.institution')),
                ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='academics.researcharea')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
            },
        ),
    ]
