# Generated by Django 6.0.6 on 2026-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. CREATE, UPDATE, DELETE, LOGIN, LOGOUT', max_length=50)),
                ('module', models.CharField(help_text='e.g. INSTITUTION, MOU, OPPORTUNITY, USER', max_length=100)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
