# Generated by Django 6.0.6 on 2026-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
